services:
  xiangyao:
    build:
      context: ".."
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
    - "ASPNETCORE_URLS=http://*:5000"
    command:
    - "--provider=docker"
    network_mode: "host"
    container_name: "xiangyao"

  traefik:
    image: "docker.io/traefik:v3.0"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: "traefik"
    command:
      - "--log.level=WARNING"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:6000"
    network_mode: "host"

  nginx_backend:
    image: "docker.io/nginx:alpine"
    labels:
    - "xiangyao.enable=true"
    - "xiangyao.cluster.port=80"
    - "xiangyao.cluster.schema=http"
    - "xiangyao.routes.nginx_backend.match.host=nginx_backend:5000"
    - "xiangyao.routes.nginx_backend.match.path={**catch-all}"
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.http.routers.nginx_backend.rule=Host(`nginx_backend:6000`)"
    - "traefik.http.routers.nginx_backend.entrypoints=web"
