variables:
  tag: "$(Build.BuildNumber)"
  tagArm: "$(Build.BuildNumber)-arm64"

parameters:
- name: pipelineType
  displayName: "Pipeline Type"
  type: string

jobs:
- job: Build
  displayName: 'Docker Build'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub'
      repository: 'fallenwood/xiangyao'
      ${{ if eq(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build And Push'
        command: 'buildAndPush'
      ${{ if ne(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build'
        command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(tag)
        latest

  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub'
      repository: 'fallenwood/xiangyao'
      ${{ if eq(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build And Push'
        command: 'buildAndPush'
      ${{ if ne(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build'
        command: 'build'
      Dockerfile: '**/Dockerfile.distroless'
      tags: |
        $(tag)-distroless
        latest-distroless


  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub'
      repository: 'fallenwood/xiangyao'
      ${{ if eq(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build And Push'
        command: 'buildAndPush'
      ${{ if ne(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build'
        command: 'build'
      Dockerfile: '**/Dockerfile.nativeaot'
      tags: |
        $(tag)-nativeaot
        latest-nativeaot

  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub'
      repository: 'fallenwood/xiangyao'
      ${{ if eq(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build And Push'
        command: 'buildAndPush'
      ${{ if ne(parameters.pipelineType, 'Official') }}:
        displayName: 'Docker Build'
        command: 'build'
      Dockerfile: '**/Dockerfile.arm64'
      tags: |
        $(tagArm)
